### ISSUE TITLE
数据库为什么不用room呢？

### ISSUE THREAD

**Issue by bingdu0** [CarGuo/GSYGithubAppKotlin#10]
大佬，数据库为什么不用room呢？换room 有种找到组织的感觉。预计什么时候发布release版？

**Comment by CarGuo** [comment]
现在已经有release版本了。

因为react native版本的用的也是realm，好比对。

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppKotlin/blob/master/VERSION.md

https://www.pgyer.com/XGtw
