### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by tustlitao** [CarGuo/GSYGithubAppKotlin#15]
有乱码

**Comment by CarGuo** [comment]
哪里乱码？

**Comment by tustlitao** [comment]
我不知道咋上传图片，在打开的时候点别人的项目，详情信息那一面就是中文乱码
2018.09.12 ç”±äºŽiOSç³»ç»Ÿé™åˆ¶äº†æ³¨å†Œæœ¬åœ°æŽ¨é€çš„æ•°é‡ï¼Œæœ€å¤§çš„æ³¨å†Œé‡ä¸º64æ¡ï¼Œä¸”ä¸€æ—¦è¶…å‡º64æ¡ï¼Œæ‰€æœ‰çš„æŽ¨é€éƒ½å°†å¤±æ•ˆï¼Œæ•…è€Œåœ¨æ·»åŠ æŽ¨é€çš„æ—¶å€™åšäº†ä¸€ä¸ªåˆ¤æ–­ï¼Œè¶…è¿‡64æ¡åŽï¼Œå°†ä¸æ·»åŠ ï¼Œä»¥å…å½±å“å·²ç»æ·»åŠ çš„æŽ¨é€ã€‚

å‰è¨€

æœ€è¿‘é¡¹ç›®ä¸­æ¶‰åŠåˆ°äº†æœ¬åœ°é€šçŸ¥çš„åŠŸèƒ½ï¼Œç´¢æ€§å°±æ¨¡ä»¿ç³»ç»Ÿé—¹é’Ÿå†™äº†ä¸ªdemoï¼Œå¯¹äºŽiOSç³»ç»Ÿé—¹é’Ÿï¼Œåº”è¯¥éƒ½æ¯”è¾ƒç†Ÿæ‚‰ï¼Œè¯¥demoï¼ŒåŸºæœ¬å®žçŽ°äº†ç³»ç»Ÿé—¹é’Ÿçš„å…¨éƒ¨åŠŸèƒ½ã€‚è¯¥de
就像这个样子
你要图片的话可以加我qq1037478055

**Comment by CarGuo** [comment]
哪个项目，我直接去瞄一瞄😁
