### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by tustlitao** [CarGuo/GSYGithubAppKotlin#16]
详情信息中文出现乱码

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppKotlin/issues/15   可以麻烦提供下截图吗？？

**Comment by tustlitao** [comment]
![image](https://user-images.githubusercontent.com/28053253/49647156-892a8300-fa5c-11e8-8884-4af98d30c7b4.png)

**Comment by CarGuo** [comment]
看来是本地html的浏览器兼容问题，我看了这边目前没出现，多谢提出问题
