### ISSUE TITLE
android api 兼容性问题 系统弹窗

### ISSUE THREAD

**Issue by zhangle1** [CarGuo/GSYGithubAppKotlin#26]
具体地址g.co/dev/appcompat ...
可以先用这个解决下反射引起的弹窗问题..
    private void closeAndroidPDialog(){
        if (Build.VERSION.SDK_INT >= 28){
        try {
            Class aClass = Class.forName("android.content.pm.PackageParser$Package");
            Constructor declaredConstructor = aClass.getDeclaredConstructor(String.class);
            declaredConstructor.setAccessible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            Class cls = Class.forName("android.app.ActivityThread");
            Method declaredMethod = cls.getDeclaredMethod("currentActivityThread");
            declaredMethod.setAccessible(true);
            Object activityThread = declaredMethod.invoke(null);
            Field mHiddenApiWarningShown = cls.getDeclaredField("mHiddenApiWarningShown");
            mHiddenApiWarningShown.setAccessible(true);
            mHiddenApiWarningShown.setBoolean(activityThread, true);
        } catch (Exception e) {
            e.printStackTrace();
        }

        }
    }

**Comment by CarGuo** [comment]
？现在是哪里导致问题？

**Comment by zhangle1** [comment]
就是提示appcompat  v7不兼容.. 小米新系统

**Comment by CarGuo** [comment]
好的，thx

**Comment by zhangle1** [comment]
应该是新版本的android手机 都会有这个问题  g.co/dev/appcompat  这是谷歌说明的..
