### ISSUE TITLE
dagger  疑问

### ISSUE THREAD

**Issue by zhangle1** [CarGuo/GSYGithubAppKotlin#28]
大佬我照你项目的写法，尝试写自己的项目

    @Named("main")
    @Provides
    fun providerMainFragmentList():List<Fragment>{
        return listOf(HomeFragment(),HomeFragment(),HomeFragment(),HomeFragment(),HomeFragment())
     }

    @Provides
    @Named("home")
    fun  providerHomeFragmentList():List<Fragment>{
        return listOf(HomeRecommendListFragment(),HomeRecommendListFragment(),HomeRecommendListFragment(),HomeRecommendListFragment())
    }

    @field:[Inject Named("home")]
    lateinit var homeFragmentList: MutableList<Fragment>

    @field:[Inject Named("main")]
    lateinit var mainFragmentList: MutableList<Fragment>

如果不旋转屏幕是可以正常注入fragment以及activity.

也就是主页activity->嵌套5个fragment->嵌套4个fragment 
当屏幕发生旋转时  崩溃并提示   Caused by: kotlin.UninitializedPropertyAccessException: lateinit property dispatchingAndroidInjector has not been initialized..
当主页activity->嵌套5个fragment  不加载4个fragment时是可以正常旋转的。。

**Comment by CarGuo** [comment]
没有配置manifest上的configure吧
