### ISSUE TITLE
CMakeLists.txt问题

### ISSUE THREAD

**Issue by zlc921022** [CarGuo/GSYGithubAppKotlin#33]
Cause: executing external native build for cmake E:\project\GSYGithubAppKotlin-master\app\CMakeLists.txt
这个文件编译和运行时候报错

**Comment by CarGuo** [comment]
需要配置CMake编译环境

**Comment by zlc921022** [comment]
怎么配置




| |
zlc921022
邮箱：zlc921022@163.com
|

签名由 网易邮箱大师 定制

在2019年04月19日 20:42，Shuyu Guo 写道：

需要配置CMake编译环境

**Comment by CarGuo** [comment]
网上就有，请自行谷歌
