### ISSUE TITLE
登录提示SSL handleshake aborted:xxx connection reset by peer

### ISSUE THREAD

**Issue by docwei2050** [CarGuo/GSYGithubAppKotlin#44]
按要求配置了：Clientid和CLIENT_SECRET，
cmake环境也已经配置

build apk安装后登录提示 如下：
SSL handleshake aborted:xxx connection reset by peer

烦请大佬指导下，谢谢！

**Comment by 1136346879** [comment]
> 按要求配置了：Clientid和CLIENT_SECRET，
> cmake环境也已经配置
> 
> build apk安装后登录提示 如下：
> SSL handleshake aborted:xxx connection reset by peer
> 
> 烦请大佬指导下，谢谢！

SSL handshake aborted: ssl=0xe4af32c8: I/O error during system call, Connection reset by peer

哥们我的也是这样  如何解决的？

**Comment by 1136346879** [comment]
vpn打开的问题  我的  解决了 可以登陆了

**Comment by CarGuo** [comment]
1、确定你申请的 ClientId 和 ClientSecret 是正确的。

2、确定正常使用用户名密码登陆或者 OAuth 登陆。

3、Connection refused 的情况请更换网络环境。

> **The message 'Connection Refused' has two main causes:**
> 
> - **Nothing is listening on the IP:Port you are trying to connect to.**
> 
> - **The port is blocked by a firewall.**



### Http 请求 422 请检查申请的 ClientId、 ClientSecret，登陆用用户名和密码，不用使用邮箱；授权登记方式记得 readme 中的 Authorization callback URL 一栏必须填入 `gsygithubapp://authed`


### ` Connection Refused` 问题是Github Api 和我们天朝网络的兼容问题，建议稍后再试或者换个网络环境（wifi、4G、电信/移动/联通）
