### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by 1136346879** [CarGuo/GSYGithubAppKotlin#55]
CMake Error in CMakeLists.txt:
The CMAKE_C_COMPILER:
/Users/ddd/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
is not a full path to an existing compiler tool.
Tell CMake where to find the compiler by setting either the environment
variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
the compiler, or to the compiler name if it is in the PATH.

**Comment by CarGuo** [comment]
readme 写着最后记得配置 CMake 环境哦

**Comment by 1136346879** [comment]
![image](https://user-images.githubusercontent.com/15826462/79712145-b350ae00-82fc-11ea-9d74-d4ee68156aca.png)
都已已经an'zhuan'f安装  cmake
需要环境变量？

**Comment by CarGuo** [comment]
https://blog.csdn.net/laibowon/article/details/79939962

**Comment by 1136346879** [comment]
已好  谢谢
