### ISSUE TITLE
Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://api.github.com/authorizations}

### ISSUE THREAD

**Issue by 1136346879** [CarGuo/GSYGithubAppKotlin#56]
项目正常运行后 登录返回 
Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://api.github.com/authorizations}
应该是没有授权
toast提示     <string name="error_401">[401错误可能: 未授权 \\ 授权登录失败 \\ 登录过期]</string>
楼主，麻烦看看 是不是还有什么操作没有处理？
CLIENT_ID
CLIENT_SECRET
两个数据均以正确填写

**Comment by CarGuo** [comment]
1、确定你申请的 ClientId 和 ClientSecret 是正确的。

2、确定正常使用用户名密码登陆或者 OAuth 登陆。

3、Connection refused 的情况请更换网络环境。

> **The message 'Connection Refused' has two main causes:**
> 
> - **Nothing is listening on the IP:Port you are trying to connect to.**
> 
> - **The port is blocked by a firewall.**



### Http 请求 422 请检查申请的 ClientId、 ClientSecret，登陆用用户名和密码，不用使用邮箱；授权登记方式记得 readme 中的 Authorization callback URL 一栏必须填入 `gsygithubapp://authed`


### ` Connection Refused` 问题是Github Api 和我们天朝网络的兼容问题，建议稍后再试或者换个网络环境（wifi、4G、电信/移动/联通）
