### ISSUE TITLE
Build Config field cannot have a null parameter

### ISSUE THREAD

**Issue by w910820618** [CarGuo/GSYGithubAppKotlin#59]
buildConfigField "String", "CLIENT_ID", properties.getProperty("CLIENT_ID")
        buildConfigField "String", "CLIENT_SECRET", properties.getProperty("CLIENT_SECRET")

构建的时候这两行报错，提示值为空

**Comment by CarGuo** [comment]
https://github.com/CarGuo/GSYGithubAppKotlin#编译运行流程
